from ..model import Model
import json, os, shutil
from pathlib import Path
from typing import List, Dict, Any, Literal, Optional

import numpy as np

from abacustest import AbacusSTRU, WriteInput, ReadInput, RESULT
from abacustest.constant import RECOMMAND_IMAGE, RECOMMAND_COMMAND, RECOMMAND_MACHINE
from abacustest.lib_model.comm import copy_abacusjob, get_largest_vacuum_dir
from abacustest.lib_data.grid import Potential

EFIELD_DIRECTION_MAP = ["a", "b", "c"]

class WorkFuncModel(Model):
    @staticmethod
    def model_name(): # type: ignore
        '''
        Name of the model, which will be used as the subcommand
        '''
        return "workfunc"
    
    @staticmethod
    def description(): # type: ignore
        '''
        Description of the model
        '''
        return "Prepare and postprocess the work function calculation"
    
    @staticmethod
    def prepare_args(parser):
        '''
        Add arguments for the prepare subcommand
        The arguments can not be command, model, modelcommand 
        '''
        parser.description = "Prepare the inputs for the elastic calculation."
        parser.add_argument('-j', '--job', default=[], action="extend", nargs="*", help='the paths of ABACUS jobs, should contain INPUT, STRU, or KPT, and pseudopotential and orbital files')
        parser.add_argument("--vacuum", default="c", choices=["a", "b", "c", "auto"], help="The direction of the elastic calculation, default is c. If set to auto, the direction will try to be determined automatically.")
        parser.add_argument("--dipole-corr", action="store_true", help="Whether to use dipole correction for the elastic calculation, default is not using.")
        parser.add_argument("--image", type=str, default=RECOMMAND_IMAGE, help="The image to use for the Bohrium job, default is %s" % RECOMMAND_IMAGE)
        parser.add_argument("--machine", type=str, default=RECOMMAND_MACHINE, help="The machine to use for the Bohrium job, default is 'c32_m64_cpu'.")
        parser.add_argument("--abacus_command", type=str, default=RECOMMAND_COMMAND, help=f"The command to run the Abacus job, default is '{RECOMMAND_COMMAND}'.")
        return parser
    
    def run_prepare(self,params):
        '''
        Run the model with the given parameters
        '''
        if not params.job:
            raise ValueError("No job specified, please use -j or --job to specify the job paths.")
        
        paths = []
        for job in params.job:
            if not os.path.isdir(job):
                raise ValueError("The job path is not a directory: %s" % job)
            paths.append(prep_abacus_workfunc_calc(job, params.vacuum, params.dipole_corr))
        
        setting = {
            "save_path": "results",
            "run_dft": []
        }
        
        for path in paths:
            setting["run_dft"].append({
                "ifrun": True,
                "example": str(path),
                "command": params.abacus_command,
                "image": params.image,
                "bohrium": {
                    "scass_type": params.machine,
                    "job_type": "container",
                    "platform": "ali"
                }
            })
        
        setting_file = "setting.json"
        json.dump(setting, open(setting_file, "w"), indent=4)
        print("\nThe inputs are generated in", ", ".join(params.job))
        print(f"You can modify '{setting_file}', and execute below command to run the abacustest to submit all jobs to bohrium:\n\tabacustest submit -p setting.json\n")
        print(f"After finishing the calculations, you can enter the results directory, \nand run below command below to postprocess the work function results:\n\tabacustest model elastic post -j {' '.join(params.job)}\n")
        
    
    def postprocess_args(parser):
        '''
        Add arguments for the postprocess subcommand
        The arguments can not be command, model, modelcommand 
        '''
        parser.description = "Postprocess the elastic calculation results."
        parser.add_argument('-j', '--job', default=[], action="extend", nargs="*", help='the paths of the job directories, should contain the results of deformed structures generated by the prepare step.')
        return parser   

    def run_postprocess(self,params):
        '''
        Parse the parameters and run the postprocess process'''
        if not params.job:
            raise ValueError("No job specified, please use -j or --job to specify the job paths.")
        
        results_all = {}
        for job in params.job:
            if not os.path.isdir(job):
                raise ValueError("The job path is not a directory: %s" % job)
            
            results, plot_path, pot_file, plot_data_file = post_workfunc_calc(job)
            results_all[job] = results
        
        json.dump(results_all, open("metrics.json", "w"), indent=4)
        print("\nThe postprocess is done. The metrics are saved in 'metrics.json'.")


def prep_abacus_workfunc_calc(job: Path, vacuum_dir: Literal["a", "b", "c", "auto"] = "c", dipole_corr: bool = False) -> Path:
    
    if "workfunc_job" in os.listdir(job):
        print("Old workfunc_job directory found, remove and recreate it.")
        shutil.rmtree(Path(job) / "workfunc_job")
    
    workfunc_dir = Path(os.path.join(job, "workfunc_job")).absolute()
    copy_abacusjob(job, workfunc_dir, out_dir=False)

    input_params = ReadInput(os.path.join(workfunc_dir, "INPUT"))
    if input_params.get("nspin", 1) not in [1, 2]:
        raise ValueError("Only 1 or 2 spin is supported.")

    input_params['calculation'] = 'scf'
    input_params['out_pot'] = 2

    # Find vacuum direction in automatic mode
    if vacuum_dir == 'auto':
        stru_file = os.path.join(workfunc_dir, input_params.get('stru_file', "STRU"))
        stru = AbacusSTRU.read(stru_file)
        direction, max_vacuum_cart = get_largest_vacuum_dir(coords=stru.coords, cell=stru.cell)
        prep_info = {'vacuum_dir': direction}
        print(f"Automatically identified the vacuum along {direction} direction in {stru_file}")
    else:
        prep_info = {'vacuum_dir': vacuum_dir}
    
    # Dump vacuum direction for postprocess
    with open(os.path.join(workfunc_dir, "prep_info.json"), "w") as f:
        json.dump(prep_info, f, indent=2)
    
    if dipole_corr:
        input_params['efield_flag'] = 1
        input_params['dip_cor_flag'] = 1
        if vacuum_dir in ['a', 'b', 'c']:
            input_params['efield_dir'] = EFIELD_DIRECTION_MAP.index(vacuum_dir)
        elif vacuum_dir == 'auto':
            input_params['efield_dir'] = EFIELD_DIRECTION_MAP.index(direction)
        else:
            raise ValueError("Invalid vacuum direction: %s" % vacuum_dir)
        input_params['efield_amp'] = 0.0 # Automatically determine electric field strength
        input_params['efield_pos_max'] = None # Automatically determine electric field position
        input_params['efield_pos_dec'] = None # Automatically determine range of electric field
    
    WriteInput(input_params, os.path.join(workfunc_dir, "INPUT"))

    return workfunc_dir

def post_workfunc_calc(job: Path, jobtype: Literal['abacus', 'vasp']="abacus") -> Dict[str, Any]:
    # Postprocess calculation to obtain work function data
    if jobtype == "abacus":
        workfunc_job = os.path.join(job, "workfunc_job")
        results = RESULT(fmt="abacus", path=workfunc_job)

        if results['normal_end'] is not True or results['converge'] is not True:
            raise RuntimeError("ABACUS calculation didn't end normally or didn't reached SCF converge.")

        input_params = ReadInput(os.path.join(workfunc_job, "INPUT"))
        pot_file = os.path.join(workfunc_job, f"OUT.{input_params.get('suffix', 'ABACUS')}/ElecStaticPot.cube")
        pot = Potential.from_cube(pot_file)

        prep_info = json.load(open(os.path.join(workfunc_job, "prep_info.json")))
        vacuum_dir = prep_info['vacuum_dir']
        ave_elec_stat, coord_direct = pot.profile1d(axis=vacuum_dir, average=True)
        ave_elec_stat = - ave_elec_stat # consider negative charge of electron
    elif jobtype == "vasp":
        # TODO
        pass
    else:
        raise ValueError(f"Unsupported job type: {jobtype}")

    profile_data_file = os.path.join(workfunc_job, "profiled.dat")
    with open(profile_data_file, "w") as f:
        f.write(f"{'fraction_coord':>16s}{'ave_elec_stat':>16s}\n")
        for i in range(len(coord_direct)):
            f.write(f"{coord_direct[i]:16.8f}{ave_elec_stat[i]:16.8f}\n")

    work_function_results = calculate_work_functions(ave_elec_stat,
                                                     fermi_energy=results['efermi'])

    plot_path = plot_averaged_elecstat_pot(coord_direct,
                                           ave_elec_stat,
                                           results['efermi'],
                                           axis=vacuum_dir,
                                           work_function_results=work_function_results,
                                           plot_filename=os.path.join(workfunc_job, "elecstat_pot_profile.png"))
    
    return work_function_results, plot_path, pot_file, profile_data_file

def identify_potential_plateaus(
    averaged_potential: List,
    threshold: float = 0.01
):
    """
    Identify plateaus in the electrostatic potential using derivative of the averaged electrostatic potential.
    """
    pot_derivatives = []
    n_points = len(averaged_potential)
    stepsize = 1 / (n_points - 1)
    for i in range(n_points):
        backward_idx = i - 1
        forward_idx = 0 if i == n_points - 1 else i + 1
        pot_derivative = (averaged_potential[forward_idx] - averaged_potential[backward_idx]) / (stepsize * 2.0)
        pot_derivatives.append(pot_derivative)
    
    is_plateau = [abs(deriv) < threshold for deriv in pot_derivatives]

    plateau_ranges = []
    in_plateau, start_idx = False, None
    for i in range(n_points):
        if is_plateau[i] and not in_plateau:
            in_plateau = True
            start_idx = i
        elif not is_plateau[i] and in_plateau:
            in_plateau = False
            if not start_idx == i - 1:
                plateau_ranges.append((start_idx, i-1))
                start_idx = None
        elif is_plateau[i] and i == n_points - 1:
            if not start_idx == i - 1:
                plateau_ranges.append((start_idx, i))
                in_plateau, start_idx = False, None
    
    if len(plateau_ranges) > 0:
        if plateau_ranges[-1][1] == n_points - 1:
            if len(plateau_ranges) > 1:
                combined_plateau = (plateau_ranges[-1][0] - n_points, plateau_ranges[0][1])
                plateau_ranges[0] = combined_plateau
                plateau_ranges.pop()
    
    return plateau_ranges


def calculate_work_functions(averaged_potential: List, fermi_energy):
    """
    Calculate the work function from the averaged electrostatic potential.
    Dipole correction is suppoted and multiple plateau of electrostatic potential can be identified.
    """
    work_function_results = []
    plateau_ranges = identify_potential_plateaus(averaged_potential, threshold=0.01)
    for plateau_range in plateau_ranges:
        plateau_start, plateau_end = plateau_range
        plateau_averaged_potential = np.average(averaged_potential[plateau_start:plateau_end])
        work_function_results.append({'work_function': plateau_averaged_potential - fermi_energy,
                                      'plateau_start_fractional': plateau_start / len(averaged_potential),
                                      'plateau_end_fractional': plateau_end / len(averaged_potential)})
    
    return work_function_results


def plot_averaged_elecstat_pot(
    coord: np.ndarray,
    averaged_elecstat_data: np.ndarray,
    efermi: float,
    axis: Literal['a', 'b', 'c'] = 'c',
    work_function_results: Optional[List[Dict[str, float]]] = None,
    plot_filename: Optional[str] = "elecstat_pot_profile.png"
) -> Path:
    import matplotlib.pyplot as plt
    plt.figure(figsize=(8, 4))
    plt.plot(coord, averaged_elecstat_data, label='Average electrostatic potential')
    plt.axhline(y=efermi, linestyle='--', color='gray', alpha=0.5, label=f'Fermi Energy (={efermi:.2f} eV)')
    plt.xlim(min(coord), max(coord))
    plt.xlabel("Fractional coordinate along " + axis)
    plt.ylabel("Electrostatic potential (eV)")

    if work_function_results is not None:
        for result in work_function_results:
            # Calculate position of center of plateau
            start_idx = int(result['plateau_start_fractional'] * (len(coord) - 1))
            end_idx = int(result['plateau_end_fractional'] * (len(coord) - 1))
            mid_idx = (start_idx + end_idx) // 2
            x_mid = coord[mid_idx]
            
            plateau_potential = averaged_elecstat_data[mid_idx]
            work_func = result['work_function']
            
            # Draw arrow between plateau and Fermi energy
            plt.annotate('', 
                        xy=(x_mid, efermi), 
                        xytext=(x_mid, plateau_potential),
                        arrowprops=dict(arrowstyle='<->', color='black', lw=1.5))
            
            # Decide position of annotated text
            x_range = max(coord) - min(coord)
            offset = x_range * 0.02
            if x_mid + offset <= max(coord):
                text_x = x_mid + offset
                ha_align = 'left'
            else:
                text_x = x_mid - offset
                ha_align = 'right'
            
            text_y = (efermi + plateau_potential) / 2
            
            plt.text(text_x, text_y, f'{work_func:.2f} eV', 
                     fontsize=10, ha=ha_align, va='center')
    

    plt.legend(loc='best')
    plt.tight_layout()
    plt.savefig(plot_filename, dpi=300)
    plt.close()

    return Path(plot_filename).absolute()
